- hosts: elk_master_nodes
  roles:
    - role: elastic.elasticsearch
  vars:
    es_version: 7.10.0
    es_enable_xpack: false
    es_data_dirs:
      - "/data/elasticsearch/data"
    es_log_dir: "/data/elasticsearch/logs"
    es_java_install: true
    es_heap_size: "1g"
    es_config:
      cluster.name: "elk-cluster-chakouki-dahamou-dahouch"
      cluster.initial_master_nodes: ["3.239.37.225:9300"]
      discovery.seed_hosts: ["3.239.37.225:9300","3.237.99.222:9300","3.238.76.108:9300"]
      http.port: 9200
      node.data: false
      node.master: true
      bootstrap.memory_lock: false
      network.host: '0.0.0.0'
    es_plugins:
     - plugin: ingest-attachment

- hosts: elk_data_nodes
  roles:
    - role: elastic.elasticsearch
  vars:
    es_version: 7.10.0
    es_enable_xpack: false
    es_data_dirs:
      - "/data/elasticsearch/data"
    es_log_dir: "/data/elasticsearch/logs"
    es_java_install: true
    es_config:
      cluster.name: "elk-cluster-chakouki-dahamou-dahouch"
      cluster.initial_master_nodes: ["3.239.37.225:9300"]
      discovery.seed_hosts: ["3.239.37.225:9300","3.237.99.222:9300","3.238.76.108:9300"]
      http.port: 9200
      node.data: true
      node.master: false
      bootstrap.memory_lock: false
      network.host: '0.0.0.0'
    es_plugins:
      - plugin: ingest-attachment
